version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: web2_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - mongodb
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  mongo_data: