services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: web2_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6-focal
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "3000:8081"
    depends_on:
      - postgres
      - mongo
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/web2_db
      - MONGODB_URI=mongodb://mongo:27017/web2_logs
      - JWT_SECRET=Xkj8$9mP#vQ2@hL5^zN7&wR3*sT1!aB6%yC4+dE8~fG9
      - NODE_ENV=development
      - POSTGRES_DB=web2_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - PORT=8081
    command: npm start

volumes:
  postgres_data:
  mongo_data:
  node_modules_data: {}
